[project]
name = "spectrumanalyser"
version = "0.1.0"
description = ""
authors = [
    {name = "Erkki Nurmi",email = "183535537+eki-77@users.noreply.github.com"}
]
readme = "README.md"
requires-python = "^3.10"
dependencies = [
    "cowsay (>=6.1,<7.0)",
    "numpy (==2.2)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=9.1.1,<10.0.0)"
]
