   '''
    valmisteltu = testi.valmistele(testi.data)
    print("valmistellun pituus", len(valmisteltu))
    #print(testi.fft([0,1,2,3]))
    #print(testi.data)
    #muunnos = testi.fft(testi.data[:16384])
    muunnos = testi.fft(valmisteltu)
    print("muunnoksen pituus", len(muunnos))
    tulokset = testi.skaalaa_reaaliluvuksi(muunnos)
    print("tulosten pituus", len(tulokset))
    print(valmisteltu[:16])
    print(tulokset[:16])
    print(len(tulokset))
    print(type(muunnos[0]))
    print(type(valmisteltu[0]))
    print(type(tulokset[0]))
    #print(tulokset[-16:])
    #print(valmisteltu[-16:])
    print(max(tulokset))
    print(min(tulokset))
    korit = testi.anna_taajuuskorit(tulokset)
    print("koreja:", len(korit))
    print(korit[:10])
    print(korit[-10:])
    huiput = testi.etsi_maksimit(tulokset)
    print(len(huiput))
    print(huiput)
    testi.plottaa_tulokset(tulokset, korit)
    #plt.plot(tulokset)
    #plt.show()
    #print(hanning(16))
    #print(type(hanning(16) * tulokset[:16]))
    #print(list(hanning(16) * tulokset[:16]))
    #print(testi.kahden_potenssi(5))
    #testi = list(hanning(16) * tulokset[:16])
    #print(testi + [0.0] * 5)
    '''

